apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-server
  labels:
    app: house-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-server
  template:
    metadata:
      labels:
        app: house-server
    spec:
      imagePullSecrets:
        - name: churrer-registry
      containers:
        - name: server
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.15"
              ephemeral-storage: "2Gi"
            limits:
              memory: "200Mi"
              cpu: "0.50"
              ephemeral-storage: "2Gi"
          image: ghcr.io/danilomurer/churrer.xyz-server:0.5.0
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
          env:
            - name: DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: postgres-auth
                  key: connection_string
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-auth
                  key: username
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-auth
                  key: password
      automountServiceAccountToken: false
