apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-admin
spec:
  type: kv-v2

  # mount path
  mount: kv

  # path of the secret
  path: churrer.xyz/admin

  # dest k8s secret
  destination:
    name: admin-auth
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: house/vault-auth