apiVersion: apps/v1
kind: Deployment
metadata:
  name: house
  labels:
    app: house
spec:
  selector:
    matchLabels:
      app: house
  template:
    metadata:
      labels:
        app: house
    spec:
      imagePullSecrets:
        - name: churrer-registry
      containers:
      - name: house-client
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "120Mi"
        image: ghcr.io/danilomurer/churrer.xyz:0.3.1
        ports:
        - containerPort: 3000
#      - name: house-server
#        resources:
#          requests:
#            memory: "100Mi"
#          limits:
#            memory: "120Mi"
#        image: git.churrer.xyz/churrer.xyz/house/house-server:0.2.0
#        ports:
#          - containerPort: 3000
#        env:
#          - name: DATABASE_HOST
#            valueFrom:
#              configMapKeyRef:
#                name: mongo-config
#                key: mongo-host
#          - name: DATABASE_NAME
#            value: "house"
#          - name: DATABASE_USERNAME
#            valueFrom:
#              secretKeyRef:
#                name: mongo-auth
#                key: username
#          - name: DATABASE_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: mongo-auth
#                key: password