apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-silverbullet-auth
spec:
  type: kv-v2

  # mount path
  mount: kv

  # path of the secret
  path: silverbullet/auth

  # dest k8s secret
  destination:
    name: silverbullet-auth
    create: true

  # static secret refresh interval
  refreshAfter: 30s

  # Name of the CRD to authenticate to Vault
  vaultAuthRef: silverbullet/vault-auth